
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./nexthauth/Providers";
import { Poppins, Work_Sans } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster"
// import Sidenav from "./components/Sidenav";
import { ThemeProvider } from "next-themes";
import UserContext from "./components/UserContext";


const customPoppins = Poppins({
  subsets: ['latin'],
  weight: "400",
  variable: '--custom_poppins',
});

const workSans = Work_Sans({
  subsets:['latin'],
  weight: ["400", "600"],
  variable: '--work_sans',
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Lendsqr Test Project",
  description: "Generated by create next app for testing",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      
        // style={{color-scheme:"dark"}}
        className={cn(
          workSans.variable,
          customPoppins.variable, // Corrected usage of cn
          geistSans.variable,
          geistMono.variable,
          // "dark",
          "font-sans",
          "antialiased", // This should be a normal string argument
          {"debug-screens":process.env.NODE_ENV === 'development'}
        )}
      ><Providers>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main>
              <UserContext>
                {children}
              </UserContext>
            </main>
              <Toaster />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
